[mgr]
show_hidden = true

[opener]
browser = [
	{ run = "waterfox %s", orphan = true, for = "unix", desc = "Open with browser" }
]
edit = [
	{ run = "nvim %*", block = true, for = "unix", desc = "Edit" }
]

[open]
rules = [
	{ url = "*flamegraph.svg", use = [ "browser", "open" ] },
	{ mime = "image/jxl", use = [ "open" ] },
	{ mime = "text/plain", use = [ "edit" ] }
]
